Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -80,7 +80,7 @@ jobs:
       - name: Health Check
         run: |
           echo "Checking service health..."
-          curl --fail http://localhost:${{ env.APP_PORT }}/health || (echo "Health check failed!" && exit 1)
+          curl --fail http://localhost:${{ secrets.APP_PORT }}/health || (echo "Health check failed!" && exit 1)
 
       - name: Cleanup Build Directory
         if: ${{ success() }}
